list            : $/martin/settings/models/parameter/columns.yaml
modelClass      : Martin\Settings\Models\Parameter
title           : Settings & Parameters
recordUrl       : martin/settings/parameters/update/:id
noRecordsMessage: backend::lang.list.no_records
recordsPerPage  : 20
showSetup       : true
showSorting     : true

defaultSort:
    column   : id
    direction: asc

toolbar:
    buttons: list_toolbar
    search :
        prompt: backend::lang.list.search_prompt